---
- name: Add Dropbox repo in RedHat
  when: ansible_os_family == 'RedHat'
  become: true
  copy:
    src: dropbox.repo
    dest: /etc/yum.repos.d/dropbox.repo
  notify: Notify updates of Dropbox via Slack

- name: Add the GPG key for Dropbox
  when: ansible_distribution == 'Ubuntu'
  become: true
  apt_key:
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    keyserver: pgp.mit.edu
  notify: Notify updates of Dropbox via Slack

- name: Add Dropbox repo
  when: ansible_distribution == 'Ubuntu'
  become: true
  apt_repository:
    repo: "deb http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: dropbox
  notify: Notify updates of Dropbox via Slack

- name: Install Dropbox in Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  dnf:
    name: nautilus-dropbox
    state: latest
  notify: Notify updates of Dropbox via Slack

- name: Install Dropbox in CentOS
  when: ansible_distribution == 'CentOS'
  become: true
  yum:
    name: nautilus-dropbox
    state: latest
  notify: Notify updates of Dropbox via Slack

- name: Install Dropbox in Ubuntu
  when: ansible_distribution == 'Ubuntu'
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name: nautilus-dropbox
    state: latest
  notify: Notify updates of Dropbox via Slack
